# Generated by Django 3.2.14 on 2022-07-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Powerplant',
            new_name='Powerplant_USstates',
        ),
    ]
