# Generated by Django 3.2.14 on 2022-07-08 14:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0002_rename_powerplant_powerplant_usstates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_power_plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('country_long', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('gppd_idnr', models.CharField(max_length=255)),
                ('capacity_mw', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('primary_fuel', models.CharField(max_length=255)),
                ('other_fuel1', models.CharField(max_length=255)),
                ('other_fuel2', models.CharField(max_length=255)),
                ('other_fuel3', models.CharField(max_length=255)),
                ('commissioning_year', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('geolocation_source', models.CharField(max_length=255)),
                ('wepp_id', models.CharField(max_length=255)),
                ('year_of_capacity_data', models.CharField(max_length=255)),
                ('generation_gwh_2013', models.CharField(max_length=255)),
                ('generation_gwh_2014', models.CharField(max_length=255)),
                ('generation_gwh_2015', models.CharField(max_length=255)),
                ('generation_gwh_2016', models.CharField(max_length=255)),
                ('generation_gwh_2017', models.CharField(max_length=255)),
                ('generation_gwh_2018', models.CharField(max_length=255)),
                ('generation_gwh_2019', models.CharField(max_length=255)),
                ('generation_data_source', models.CharField(max_length=255)),
                ('estimated_generation_gwh_2013', models.CharField(max_length=255)),
                ('estimated_generation_gwh_2014', models.CharField(max_length=255)),
                ('estimated_generation_gwh_2015', models.CharField(max_length=255)),
                ('estimated_generation_gwh_2016', models.CharField(max_length=255)),
                ('estimated_generation_gwh_2017', models.CharField(max_length=255)),
                ('estimated_generation_note_2013', models.CharField(max_length=255)),
                ('estimated_generation_note_2014', models.CharField(max_length=255)),
                ('estimated_generation_note_2015', models.CharField(max_length=255)),
                ('estimated_generation_note_2016', models.CharField(max_length=255)),
                ('estimated_generation_note_2017', models.CharField(max_length=255)),
                ('field_37', models.CharField(max_length=255)),
                ('field_38', models.CharField(max_length=255)),
                ('field_39', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.RenameModel(
            old_name='Powerplant_USstates',
            new_name='US_states_info',
        ),
    ]
