# Generated by Django 3.2.14 on 2022-07-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0005_auto_20220711_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='capacity_m',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='commission',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='country',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='country_lo',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_5',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_6',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_7',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_8',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_9',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimated_field',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_5',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_6',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_7',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generation',
            field=models.CharField(max_length=80),
        ),
    ]
