# Generated by Django 3.2.14 on 2022-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0006_auto_20220711_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='other_fu_1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='other_fu_2',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='other_fuel',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
