# Generated by Django 3.2.14 on 2022-07-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0007_auto_20220711_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='capacity_m',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='commission',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='country_lo',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_1',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_5',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_6',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_7',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_8',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimate_9',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='estimated_field',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_6',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generati_7',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='generation',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='geolocatio',
            field=models.CharField(max_length=83, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='gppd_idnr',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='name',
            field=models.CharField(max_length=87, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='owner',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='primary_fu',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='source',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='url',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='wepp_id',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='global_power_plant_details',
            name='year_of_ca',
            field=models.CharField(max_length=91, null=True),
        ),
    ]
