# Generated by Django 3.2.14 on 2022-07-14 06:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0008_auto_20220711_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_power_plant_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_details', models.CharField(default=0, max_length=80)),
                ('country_lo', models.CharField(default=0, max_length=80)),
                ('name', models.CharField(max_length=87, null=True)),
                ('gppd_idnr', models.CharField(max_length=80, null=True)),
                ('capacity_m', models.FloatField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('primary_fu', models.CharField(max_length=80, null=True)),
                ('other_fuel', models.CharField(max_length=80, null=True)),
                ('other_fu_1', models.CharField(max_length=80, null=True)),
                ('other_fu_2', models.CharField(max_length=80, null=True)),
                ('commission', models.FloatField(null=True)),
                ('owner', models.CharField(max_length=140, null=True)),
                ('source', models.CharField(max_length=80, null=True)),
                ('url', models.CharField(max_length=254, null=True)),
                ('geolocatio', models.CharField(max_length=83, null=True)),
                ('wepp_id', models.CharField(max_length=80, null=True)),
                ('year_of_ca', models.CharField(max_length=91, null=True)),
                ('generation', models.CharField(max_length=80, null=True)),
                ('generati_1', models.FloatField(null=True)),
                ('generati_2', models.FloatField(null=True)),
                ('generati_3', models.FloatField(null=True)),
                ('generati_4', models.FloatField(null=True)),
                ('generati_5', models.FloatField(null=True)),
                ('generati_6', models.FloatField(null=True)),
                ('generati_7', models.CharField(max_length=80, null=True)),
                ('estimated_field', models.CharField(max_length=80, null=True)),
                ('estimate_1', models.CharField(max_length=80, null=True)),
                ('estimate_2', models.FloatField(null=True)),
                ('estimate_3', models.FloatField(null=True)),
                ('estimate_4', models.FloatField(null=True)),
                ('estimate_5', models.CharField(max_length=80, null=True)),
                ('estimate_6', models.CharField(max_length=80, null=True)),
                ('estimate_7', models.CharField(max_length=80, null=True)),
                ('estimate_8', models.CharField(max_length=80, null=True)),
                ('estimate_9', models.CharField(max_length=80, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Global_power_plant_details',
        ),
    ]
