# Generated by Django 3.2.14 on 2022-07-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0009_auto_20220714_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_power_plant_info',
            old_name='country_details',
            new_name='country',
        ),
    ]
