# Generated by Django 3.2.14 on 2022-07-14 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0010_rename_country_details_global_power_plant_info_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='global_power_plant_info',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geodata_app.us_states_info'),
        ),
    ]
