# Generated by Django 3.2.14 on 2022-07-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata_app', '0011_global_power_plant_info_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_power_plant_info',
            old_name='geom',
            new_name='geom_point',
        ),
    ]
