from django.db import models

from django.contrib.gis.db import models
from django.contrib.gis.geos import Point


class US_states_info(models.Model):
    region = models.CharField(max_length=2)
    division = models.CharField(max_length=2)
    statefp = models.CharField(max_length=2)
    statens = models.CharField(max_length=8)
    geoid = models.CharField(max_length=2)
    stusps = models.CharField(max_length=2)
    name = models.CharField(max_length=100)
    lsad = models.CharField(max_length=2)
    mtfcc = models.CharField(max_length=5)
    funcstat = models.CharField(max_length=1)
    aland = models.BigIntegerField()
    awater = models.BigIntegerField()
    intptlat = models.CharField(max_length=11)
    intptlon = models.CharField(max_length=12)
    geom = models.MultiPolygonField(srid=4326)

class Global_power_plant_info(models.Model):
    country = models.CharField(max_length=80,default=0)
    country_lo = models.CharField(max_length=80,default=0)
    name = models.CharField(max_length=87, null=True)
    gppd_idnr = models.CharField(max_length=80, null=True)
    capacity_m = models.FloatField( null=True)
    latitude = models.FloatField()
    longitude = models.FloatField()
    primary_fu = models.CharField(max_length=80, null=True)
    other_fuel = models.CharField(max_length=80, null=True)
    other_fu_1 = models.CharField(max_length=80, null=True)
    other_fu_2 = models.CharField(max_length=80, null=True)
    commission = models.FloatField( null=True)
    owner = models.CharField(max_length=140, null=True)
    source = models.CharField(max_length=80, null=True)
    url = models.CharField(max_length=254, null=True)
    geolocatio = models.CharField(max_length=83, null=True)
    wepp_id = models.CharField(max_length=80, null=True)
    year_of_ca = models.CharField(max_length=91, null=True)
    generation = models.CharField(max_length=80, null=True)
    generati_1 = models.FloatField( null=True)
    generati_2 = models.FloatField( null=True)
    generati_3 = models.FloatField( null=True)
    generati_4 = models.FloatField( null=True)
    generati_5 = models.FloatField( null=True)
    generati_6 = models.FloatField( null=True)
    generati_7 = models.CharField(max_length=80, null=True)
    estimated_field = models.CharField(max_length=80, null=True)
    estimate_1 = models.CharField(max_length=80, null=True)
    estimate_2 = models.FloatField( null=True)
    estimate_3 = models.FloatField( null=True)
    estimate_4 = models.FloatField( null=True)
    estimate_5 = models.CharField(max_length=80, null=True)
    estimate_6 = models.CharField(max_length=80, null=True)
    estimate_7 = models.CharField(max_length=80, null=True)
    estimate_8 = models.CharField(max_length=80, null=True)
    estimate_9 = models.CharField(max_length=80, null=True)
    geom_point = models.MultiPointField(srid=4326)
    state = models.ForeignKey(US_states_info, on_delete=models.CASCADE, null=True)
